### ISSUE TITLE
Webpack 5

### ISSUE THREAD

**Issue by iacobliviu** [bealearts/qlik-sense-webpack-plugin#1]
On webpack 5 the compiler.plugin is not exist they removed 

[webpack-cli] TypeError: compiler.plugin is not a function
    at QlikSensePlugin.apply (/project/node_modules/qlik-sense-webpack-plugin/dist/QlikSensePlugin.js:43:22)
    at createCompiler (/project/node_modules/webpack/lib/webpack.js:74:12)
    at create (/project/node_modules/webpack/lib/webpack.js:127:16)
    at webpack (/project/node_modules/webpack/lib/webpack.js:135:47)
    at WebpackCLI.f [as webpack] (/project/node_modules/webpack/lib/index.js:55:16)
    at WebpackCLI.createCompiler (/project/node_modules/webpack-cli/lib/webpack-cli.js:2191:23)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async WebpackCLI.runWebpack (/project/node_modules/webpack-cli/lib/webpack-cli.js:2321:16)
    at async Command.<anonymous> (/project/node_modules/webpack-cli/lib/webpack-cli.js:1058:13)
    at async Promise.all (index 1)

**Comment by DavidBeale** [comment]
Hi, I do not use qlik anymore. 

However if you would like to fork the project and submit a PR for webpack 5 - than i would be happy to do a major release for it.

**Comment by iacobliviu** [comment]
Hi @DavidBeale 

Yes i will do like that and i will push the code soon

Thanks

**Comment by DavidBeale** [comment]
Fixed in version v0.2.0
